apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/ernie-dev/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 17 Jan 2026 23:36:58 SAST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:60241
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 17 Jan 2026 23:36:58 SAST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /Users/ernie-dev/.minikube/profiles/minikube/client.crt
    client-key: /Users/ernie-dev/.minikube/profiles/minikube/client.key
